on: 
  pull_request:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest # machine that runs on
    steps: 
      - run: echo Hello World # specific the command that you want to run