name: Our CI

on: 
  pull_request:
  push:
    branchs:
      - master
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest # machine that runs on
    steps: 
      #- run: echo Hello World # specific the command that you want to run
      - uses: actions/checkout@v4 # actions are github repos https://github.com/actions/checkout (if pull or pushed will be checkout)
      - name: Install Python
      - uses: actions/setup-python@v5 # install a specific python version
        with: 
          python-version: "3.11" # need quotation so 3.10 will not be read as 3.1 and will be read by its entirety
      - run: python -m pip install .[test]
      - name: Run tests
      - run: python -m pytest