on:
  pull-request:
  push:
    branchs:
      - main
    workflow_dispatch:

jobs:
  test:
    name: Publishing slides
    runs-on: ubuntu-latest
    steps: 
      #- id: step1 
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5 # install a specific python version
        with:
          python-version: "3.11"
      - name: Install markdown slides
        run: pip install git+https://gitlab.com/da_doomer/markdown-slides.git
      - name: Generate slides
        run: mdslides slides.md --output_dir slides
      - uses: actions/upload-pages-artifact
        with:
          path: ./slides

  # deploy:
  #   if: github.event_name == 'push'
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - run: echo "Deploy job"
  #     - uses: actions/deploy-pages

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3